version: '3.8'

services:
  backend:
    image: battleship/backend:latest
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xms512M -Xmx1024M
    restart: always


  frontend:
    image: battleship/frontend:latest
    ports:
      - "80:80"
    restart: always