# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.csrf.CSRFFilter"

play.http.secret.key="gv1146L1kMBCrNj0VQAAj8n18whpj2QwIRkIGAo0YOk="
play.http.session.maxAge = 1h
play.http.session.cookie.secure = false
play.filters.hosts.allowed = ["*"]



play.filters.cors {
  allowedOrigins = ["*"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "X-Requested-With", "Authorization"]
  preflightMaxAge = 1 hour
}