# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.csrf.CSRFFilter"

play.http.secret.key="gv1146L1kMBCrNj0VQAAj8n18whpj2QwIRkIGAo0YOk="



play.filters.cors {
  allowedOrigins = ["http://localhost:5173"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "X-Requested-With", "Authorization"]
  preflightMaxAge = 1 hour
}